tanh_ctrl:
  ros__parameters:
    topics:
      reference: /tanh_ctrl/reference
      start_tracking: /mission/start_tracking

    model:
      mass: 2.0643076923076915
      gravity: 9.81
      force_max: 8.54858
      thrust_model_factor: 1.0
      inertia_diag: [0.02384669, 0.02394962, 0.04399995]

    allocation:
      l: 0.246073
      cq_ct: 0.016

    mission:
      takeoff_target_z: -2.0
      takeoff_z_threshold: 0.2
      takeoff_hold_time_s: 2.0
      reference_timeout_s: 0.3  
      request_interval_s: 1.0   

    position:
      horizontal:
        M_P: 2.5
        K_P: 1.0
        M_V: 8.0
        K_V: 0.5
        K_Acceleration: 1.1
        observer:
          P_V: 1.5
          L_V: 1.5
      vertical:
        M_P: 0.8
        K_P: 1.0
        M_V: 10.5
        K_V: 1.0
        K_Acceleration: 1.0
        observer:
          P_V: 4.2
          L_V: 2.5
      max_tilt_deg: 25.0

    attitude:
      tilt:
        M_Angle: 1.0
        K_Angle: 20.2
        M_AngularVelocity: 23.4
        K_AngularVelocity: 5.0
        K_AngularAcceleration: 1.0
        observer:
          P_AngularVelocity: 20.5
          L_AngularVelocity: 0.5
      yaw:
        M_Angle: 1.0
        K_Angle: 2.0
        M_AngularVelocity: 6.0
        K_AngularVelocity: 3.0
        K_AngularAcceleration: 1.0
        observer:
          P_AngularVelocity: 0.5
          L_AngularVelocity: 0.5

    filters:
      linear:
        horizontal_cutoff_hz: 10.0
        vertical_cutoff_hz: 5.0
      velocity_disturbance_cutoff_hz: 5.0
      angular_velocity_disturbance_cutoff_hz: 15.0
